### ISSUE TITLE
Tracking changes in meeting with Donal Hill

### ISSUE THREAD

**Issue by dvandyk** [eos/eos#209]
- [x] rename V10,V20,...V5T angular observables in B->D*lnu to the more common naming scheme J1s, J1c, ..., J9.
 - [x] export J1s...J9 as observables with arbitrary q2 binning
 - [ ] unify code for Bbar_q -> {D_q^*,rho,K^*} l nu
